Resources:
  CreditRecommendationAPIGatewayWebACLAssociation:
    Type: 'AWS::WAFv2::WebACLAssociation'
    DependsOn:
      - CreditRecommendationApiGateway
      - ApiGatewayDeployment
      - CreditRecommendationWebAcl
    Properties:
      ResourceArn: !Join
        - ''
        - - 'arn:'
          - !Ref 'AWS::Partition'
          - ':apigateway:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':'
          - '/restapis/'
          - !Ref CreditRecommendationApiGateway
          - /stages/${opt:stage}
      WebACLArn: !GetAtt
        - CreditRecommendationWebAcl
        - Arn